// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Man is an autogenerated mock type for the Man type
type Man struct {
	mock.Mock
}

// Talk provides a mock function with given fields: sentence
func (_m *Man) Talk(sentence string) string {
	ret := _m.Called(sentence)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(sentence)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Walk provides a mock function with given fields: road
func (_m *Man) Walk(road string) string {
	ret := _m.Called(road)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(road)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
