// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dashboard struct {
	Env           string `json:"Env"`
	OrderID       int    `json:"OrderId"`
	RequestID     int    `json:"RequestId"`
	CdType        string `json:"CdType"`
	HelmPackage   string `json:"HelmPackage"`
	Cluster       string `json:"Cluster"`
	Namespace     string `json:"Namespace"`
	Application   string `json:"Application"`
	AppVersion    string `json:"AppVersion"`
	ChartVersion  string `json:"ChartVersion"`
	ExpAppVersion string `json:"ExpAppVersion"`
	URL           string `json:"Url"`
	Datetime      int    `json:"Datetime"`
	Status        string `json:"Status"`
}

type DashboardQueryCondition struct {
	Env           *string `json:"Env"`
	Keyword       *string `json:"Keyword"`
	CdType        *string `json:"CdType"`
	Cluster       *string `json:"Cluster"`
	Namespace     *string `json:"Namespace"`
	StartDatetime *string `json:"StartDatetime"`
	EndDatetime   *string `json:"EndDatetime"`
	Status        *string `json:"Status"`
	Page          *int    `json:"Page"`
	Pagesize      *int    `json:"Pagesize"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
